### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by anusha7530** [VedantAnand17/Web3-Wallet#1]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Code%20of%20conduct.md

**Comment by Ishitagu** [comment]
hi! i would like to work on this issue please assign it to me , thank you in advance.

**Comment by KiranBaliga** [comment]
Please assign this task to me as a part of WOB24 and as requested on the thread in Discord. Thank you @VedantAnand17

**Comment by VedantAnand17** [comment]
Assigned to both, whoever sends a PR request first will get the points ✅

**Comment by Ishitagu** [comment]
@VedantAnand17 as mentioned previously the first one to raise the PR will get points . Please note that my PR was issued earlier and review the same , i would greatly appreciate  any feedback or changes which may be required.Additionally,  Please add WOB24 and Level1 labels to the PR and Issue. Thank you!

**Comment by KiranBaliga** [comment]
@Ishitagu I see that your PR is 3 minutes ahead of me. Wishing you the best! it was a good time! 🤩🫂 :-) we work one pull request at a time :-)
