### ISSUE TITLE
Improving the ui of all pages

### ISSUE THREAD

**Issue by YadlaMani** [VedantAnand17/Web3-Wallet#10]
@VedantAnand17  I would like to improve the UI of all the pages and plan to do it page by page. Could you please assign me this issue fellow 100xdevs student here

**Comment by VedantAnand17** [comment]
> @VedantAnand17  I would like to improve the UI of all the pages and plan to do it page by page. Could you please assign me this issue fellow 100xdevs student here

Assigned ✅

**Comment by YadlaMani** [comment]
@VedantAnand17 okay great

**Comment by YadlaMani** [comment]
@VedantAnand17 to do that we need to have tsconfig file so i will try to implement with other ui libraries

**Comment by VedantAnand17** [comment]
> @VedantAnand17 to do that we need to have tsconfig file so i will try to implement with other ui libraries
> 

Make a jsconfig, you can refer youtube for shadCN setup with react js

**Comment by ayush-848** [comment]
@VedantAnand17 If it is not being worked upon, Can I work on this issue??

**Comment by VedantAnand17** [comment]
> @VedantAnand17 If it is not being worked upon, Can I work on this issue??

Sure, will assign you this issue, whoever sends a good PR first will get it merged :)

**Comment by VedantAnand17** [comment]
Great work @ayush-848 👏👏 
Don't forget to follow and star ⭐ the project :)
