### ISSUE TITLE
Adding error handling, clipboard effect in Ethereum.jsx

### ISSUE THREAD

**Issue by ayush-848** [VedantAnand17/Web3-Wallet#12]
Same as the title

**Comment by ayush-848** [comment]
@VedantAnand17 please assign this to me

**Comment by VedantAnand17** [comment]
Kindly explain the issue a bit with screenshots if possible.

**Comment by ayush-848** [comment]
Error handling will the part where the code generation will take place
and 
![{CF1F211F-3253-4F6F-B28A-AB342BC26A3F}](https://github.com/user-attachments/assets/b994ebea-4ffa-4a6a-b18f-e2a917ba6413)
this will be the clipboard icon

**Comment by ayush-848** [comment]
The copy button will be disabled while the generation is taking place

**Comment by VedantAnand17** [comment]
Ohh great, you can do that after the UI changes are made in the other issues as you will be comfortable to adapt to that UI and make changes respectively

**Comment by ayush-848** [comment]
> Ohh great, you can do that after the UI changes are made in the other issues as you will be comfortable to adapt to that UI and make changes respectively

@VedantAnand17 sure that will be great

**Comment by IshuSinghSE** [comment]
loyal option daughter among olive thing need ill leave plunge urge prefer @VedantAnand17 #12

**Comment by ayush-848** [comment]
> loyal option daughter among olive thing need ill leave plunge urge prefer @VedantAnand17 #12

??

**Comment by VedantAnand17** [comment]
> loyal option daughter among olive thing need ill leave plunge urge prefer @VedantAnand17 #12

?

**Comment by IshuSinghSE** [comment]
> > loyal option daughter among olive thing need ill leave plunge urge prefer @VedantAnand17 #12
> 
> ??

sorry for the miscommunication !

**Comment by VedantAnand17** [comment]
Actually someone already solved this issue, so closing this.
But you can definitely solve the other issues :)
