### ISSUE TITLE
No Visual Feedback on Copy Seed Phrase Button Click

### ISSUE THREAD

**Issue by Sudhanshugupta26** [VedantAnand17/Web3-Wallet#13]
https://github.com/user-attachments/assets/ebb7d794-dbba-4a3e-a967-14fa70fbef5b

Description:
When I click on the "Copy Seed Phrase" button, there is no visual indication or confirmation that the button has been clicked, nor is there any feedback to confirm that the seed phrase has been successfully copied. This makes it unclear whether the action has been completed or not.

Expected Behavior:
After clicking the "Copy Seed Phrase" button, there should be some form of feedback (e.g., a temporary message like "Seed phrase copied!" or a color change on the button) to confirm the action was successful.

Steps to Reproduce:
1. Navigate to the page containing the "Copy Seed Phrase" button.
2. Click the "Copy Seed Phrase" button.
3. Observe that there is no visual or textual feedback confirming the seed phrase has been copied.

Suggested Fix:
1. Implement a notification or temporary message confirming that the seed phrase has been copied.
2. Add a visual cue to the button (e.g., change in color or icon) to indicate that it has been clicked.

Environment:
Browser: Brave
Operating System: Windows

**Comment by Sudhanshugupta26** [comment]
Assign this issue to me please @VedantAnand17

**Comment by VedantAnand17** [comment]
> Assign this issue to me please @VedantAnand17 

Assigned

**Comment by VedantAnand17** [comment]
Great work ✅

**Comment by Sudhanshugupta26** [comment]
Already done sir!
