### ISSUE TITLE
Integrating a DApp browser inside the website

### ISSUE THREAD

**Issue by ayush-848** [VedantAnand17/Web3-Wallet#15]
![image](https://github.com/user-attachments/assets/c67fdfe8-1c90-4200-b75b-34db6ad039a0)

I have made it but haven't styled it yet

**Comment by ayush-848** [comment]
@VedantAnand17 what do you think

**Comment by VedantAnand17** [comment]
Can do, but make another page section for this feature and test the loading times, execute lazy loading and you'll be good to go mp :)

**Comment by VedantAnand17** [comment]
Also, don't forget to start the repo :)

**Comment by ayush-848** [comment]
@VedantAnand17 the app doesnt have a navbar 
so should i add a button that will take it to other page

**Comment by ayush-848** [comment]
Also assign the issue to me

**Comment by VedantAnand17** [comment]
> @VedantAnand17 the app doesnt have a navbar 
> so should i add a button that will take it to other page

Or you can create a nav and I'll make it level 2

**Comment by ayush-848** [comment]
![image](https://github.com/user-attachments/assets/befbc057-609b-416e-94a6-0d62e83d7ab7)
how is it

**Comment by ayush-848** [comment]
![image](https://github.com/user-attachments/assets/a40c470e-e113-48c7-8ce0-1c2646f9b9c2)

**Comment by ayush-848** [comment]
@VedantAnand17

**Comment by VedantAnand17** [comment]
It'll be great if you create a NavBar for the redirection of this functionality...
(You can import it from libraries like MagicUI )

**Comment by ayush-848** [comment]
> It'll be great if you create a NavBar for the redirection of this functionality... (You can import it from libraries like MagicUI )

Will it be ok if I do a separate issue for it

**Comment by VedantAnand17** [comment]
> > It'll be great if you create a NavBar for the redirection of this functionality... (You can import it from libraries like MagicUI )
> 
> Will it be ok if I do a separate issue for it @VedantAnand17 

Definitely your choice but instead of two level 1s, I can give you a level 2

**Comment by VedantAnand17** [comment]
Great work @ayush-848 👏👏 
Don't forget to ⭐ the repo :)
