### ISSUE TITLE
Add Github Greeting Bot

### ISSUE THREAD

**Issue by KiranBaliga** [VedantAnand17/Web3-Wallet#16]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (WOB24 Contribution)

**Comment by VedantAnand17** [comment]
> Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (WOB24 Contribution)

Great idea 💡 
Assigned ✅

**Comment by KiranBaliga** [comment]
@VedantAnand17 I have raised the PR. Please review and action accordingly. Please add requested labels in the PR. Thanks again.

**Comment by VedantAnand17** [comment]
> @VedantAnand17 I have raised the PR. Please review and action accordingly. Please add requested labels in the PR. Thanks again.

Will assign the WoB labels soon 👍

**Comment by VedantAnand17** [comment]
Great PR @KiranBaliga 💡
Don't forget to star the repo ⭐ :)

**Comment by KiranBaliga** [comment]
@VedantAnand17 Thank you! can you add the labels to the merged PR as well.
