### ISSUE TITLE
Enhance Project Overview in README

### ISSUE THREAD

**Issue by sanjanb** [VedantAnand17/Web3-Wallet#17]
he current project overview in the README file lacks detail and clarity. This update aims to enhance the overview by providing a comprehensive description of the project, including its purpose, key features, and technologies used. The goal is to make it easier for new users and contributors to understand the project's scope and functionality. Additionally, we will ensure that the overview aligns with the latest updates and reflects any recent changes in the project.
![Screenshot 2024-10-01 181626](https://github.com/user-attachments/assets/7cdda3db-3c00-4900-8e5d-ac6c3aff6c63)

**Comment by VedantAnand17** [comment]
Great work @sanjanb 👏 
Don't forget to star the repo :) ⭐
